### PR TITLE
Move custodia package into src/ subdir and remove PYTHONPATH

### PR DESCRIPTION
**Pull request by tiran**

### CODE REVIEW

**Comment by JAORMX** [comment]
Note that without this change I am able to run the tests with tox without issues.

**Comment by tiran** [comment]
It works for me. @JAORMX please try again with a clean checkout.

```
$ git clean -xdf
$ tox
```

**Comment by tiran** [comment]
ah, I found a bug in coverage reporting

**Comment by JAORMX** [comment]
@tiran thanks, the git clean did the trick.

**Comment by simo5** [comment]
The only concern I have here is the churn that break git annotate, how hard do we need to move everything around ?

**Comment by tiran** [comment]
@simo5 ```git mv``` retains history:

```
$ git annotate src/custodia/forwarder.py | head
b20b47b1        (Simo Sorce     2015-10-02 21:30:35 -0400       1)# Copyright (C) 2015  Custodia Project Contributors - see LICENSE file
4e26c104        (Christian Heimes       2017-04-18 18:54:59 +0200       2)from __future__ import absolute_import
b20b47b1        (Simo Sorce     2015-10-02 21:30:35 -0400       3)
b20b47b1        (Simo Sorce     2015-10-02 21:30:35 -0400       4)import uuid
b20b47b1        (Simo Sorce     2015-10-02 21:30:35 -0400       5)
b20b47b1        (Simo Sorce     2015-10-02 21:30:35 -0400       6)from custodia.client import CustodiaHTTPClient
da3ebe65        (Christian Heimes       2016-09-05 11:18:08 +0200       7)from custodia.plugin import HTTPConsumer, HTTPError, PluginOption, REQUIRED
b20b47b1        (Simo Sorce     2015-10-02 21:30:35 -0400       8)
b20b47b1        (Simo Sorce     2015-10-02 21:30:35 -0400       9)
b20b47b1        (Simo Sorce     2015-10-02 21:30:35 -0400       10)class Forwarder(HTTPConsumer):
```

**Pull request merged**
