### PR TITLE
Add tests for custodia.cli

### PR DESCRIPTION
**Pull request by tiran**
I had to implement a --header argument so I could reuse our test cases. It seems like a useful option any way. 

Closes: #63 
Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by simo5** [comment]
I've run this locally in a python3.4 virtualenv and i passed just fine.
Not sure why it failed in travis.
Please rebase on current master and push it again and let's see if it was some transient error in travis

**Comment by simo5** [comment]
Note flake8 fails though, when you rebase please check travis's pep8py2 test and fix traceback/sys imports in custodia/cli/__init__.py

**Comment by tiran** [comment]
Travis has a broken version of Python. It's 3.4.2 but argparse in 3.4 has a bug that was fixed in 3.4.4. https://bugs.python.org/issue9351

**Comment by tiran** [comment]
I added better debugging (--debug flag), different return codes for HTTP error and other errors and some workaround for Python 3.4.2.

**Comment by simo5** [comment]
Can you mention the python 3.4.2 workarounds in the commit message so we know why there is "extra" stuff once we forget in a few months ?

**Pull request closed without merging**
