### PR TITLE
Add simple command line interface

### PR DESCRIPTION
**Pull request by tiran**
Please check if you are satisfied with the approach. I have to finish output formatting and error reporting.

```
$ python -m custodia.cli --help
usage: -c [-h] [--server SERVER] [--uds-urlpath UDS_URLPATH]
          [--cafile CAFILE]
          [--certfile CERTFILE] [--keyfile KEYFILE]
          {mkdir,rmdir,ls,get,set,delete} ...

Custodia command line interface

positional arguments:
  {mkdir,rmdir,ls,get,set,delete}
    mkdir               Create a container
    rmdir               Delete a container
    ls                  List content of a container
    get                 Get secret
    set                 Set or change secret
    delete              Delete a secret

optional arguments:
  -h, --help            show this help message and exit
  --server SERVER       Custodia server
  --uds-urlpath UDS_URLPATH
                        URL path for Unix Domain Socket
  --cafile CAFILE       PEM encoded file with root CAs
  --certfile CERTFILE   PEM encoded file with certs for TLS client
                        authentication
  --keyfile KEYFILE     PEM encoded key file (if not given, key is read
                        from certfile)
```

```
$ python -m custodia.cli set --help
usage: -c set [-h] name value

positional arguments:
  name        key
  value       value

optional arguments:
  -h, --help  show this help message and exit
```

### CODE REVIEW

**Comment by simo5** [comment]
I am not convinved about the mkdir/rmdir verbs, and I think I'd prefer del to delete, but otherwise looks nice.

**Comment by tiran** [comment]
It's already 'del' in the code. The message is from an older version.

How about mkcol and rmcol (like WebDAV collection ops)? create_container is too long.

**Comment by simo5** [comment]
mkcon/rmcon ?
also
newcon/delcon may work for me.

**Comment by tiran** [comment]
mkcon/rmcon sound too much like make connection. I like mkdir/rmdir. Users are already familiar with the terms. etcd uses the same verbs, too.

**Comment by simo5** [comment]
Ok.

**Comment by tiran** [comment]
CLI depends on PR #32 to provide custodia-cli entry point.

**Pull request closed without merging**
