### PR TITLE
Use PEP 440 version schema

### PR DESCRIPTION
**Pull request by tiran**
Version 0.2.dev1 is the development version of 0.2. PEP 440 version
number allows us to distribute pre-relases and development releases on
PyPI.

https://www.python.org/dev/peps/pep-0440/

Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by simo5** [comment]
I really do not like PEP 0440, it makes ordering decisions that are not alphanumeric, which means you cannot use the version directly in RPM files. as the dev version would then score *higher* than the release.

I am not sure how to reconcile using a .dev1 suffix for 0.2 without breaking the RPM NVR comparison when 0.2 is released.

If there is a canonical way to resolve this then I'd be more willing to accept this change.

**Comment by tiran** [comment]
I don't see a problem with RPM here. Why would you ever want to release a dev version as RPM? Development releases are internal test releases that can be release in DevPI or TestPyPI.

Versions like 0.1.90 for a test and development version violate Python's standard version scheme. It also cause all sorts of trouble with Python standard tools because the version number is not a pre-release number but a final release number.

**Comment by simo5** [comment]
We buil RPMs in COPR etc, for testing of prereleases too.
What about 0.1.90.dev1 ?

**Comment by simo5** [comment]
I found rules to map PEP440 version to RPMs N-V-Rs at least for Fedora.
Please rebase the commit (does not apply anymore) and I'll push to master.

**Pull request closed without merging**
