### PR TITLE
Move code from custodia script to custodia.server package

### PR DESCRIPTION
**Pull request by tiran**
All code of the custodia start script has been moved into the new
custodia.server package. The server package has a __main__ module to
make it run-able with

    $ python -m custodia.server

The config loader is more intelligent and handles special cases like
abspath() and server_url / address internally.

Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by simo5** [comment]
Can we have a custodia/custodia checked in script that calls setup.py when needed and then the main() ?

**Comment by tiran** [comment]
This PR keeps custodia/custodia and doesn't require the egg-info directory. I can add a script or a make target for that. A make target is probably better since it can do make clean egginfo run in one go without code duplication.

**Comment by simo5** [comment]
I fixed the conflicts with master and then run make, but it fails with:
F: 15, 0: Unable to import 'configparser' (import-error)

Please fix and update this PR

**Comment by tiran** [comment]
For Python 2.7 configparser is a 3rd party extension. It should be installed by requirements.txt.

**Comment by tiran** [comment]
The problem should be fixed by PR #29 and #30. pylint now runs inside a tox env with configparser installed.

**Pull request closed without merging**
