### PR TITLE
Optional GSSAPI auth for Custodia client

### PR DESCRIPTION
**Pull request by tiran**
PR based on #235

### CODE REVIEW

**Comment by tiran** [comment]
Travis CI is currently broken:

```
$ sudo apt-get -qq update
W: GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release: The following signatures were invalid: KEYEXPIRED 1515625755
W: The repository 'http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release' is not signed.
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
E: Failed to fetch store:/var/lib/apt/lists/partial/repo.mongodb.org_apt_ubuntu_dists_trusty_mongodb-org_3.4_multiverse_binary-i386_Packages  Empty files can't be valid archives
E: Some index files failed to download. They have been ignored, or old ones used instead.
``

**Comment by tiran** [comment]
@adelton please test and confirm this PR

**Comment by tiran** [comment]
thx

I'll merge the PR as soon as @adelton has confirmed that it's working for him.

**Comment by adelton** [comment]
I've backported the patch to 0.5 to test on my 0.5 setup, I tried it both with `--gssapi` and without it on machine where I've forcibly removed `python-requests-gssapi`, things look good. Thank you for making it optional.

**Comment by tiran** [comment]
thx for testing!

**Pull request merged**
