### PR TITLE
Systemd tmpfiles

### PR DESCRIPTION
**Pull request by tiran**
* Create /var/run/custodia with tmpfiles.d #96 
* Move example config files into subdirectories and run as custodia user #57

### CODE REVIEW

**Comment by tiran** [comment]
@simo5 You told me that you had a question about one PR. This is the last PR without ACK but I don't see a comment.

**Comment by simo5** [comment]
See above inline comment: "where does 447 come from ?"

**Comment by tiran** [comment]
I dropped the hard-coded uid and gid in the example.

**Comment by simo5** [comment]
There is one test failing, otherwise LGTM

**Comment by tiran** [comment]
Tests on Travis are a bit unstable. I restarted the Python 3.4 tests and it passed flawlessly. Another branch had a similar problem, but with Python 2.7.

**Pull request merged**
