### PR TITLE
Use argparse to parse custodia server arguments

### PR DESCRIPTION
**Pull request by tiran**
The server command uses argparse to parse command line arguments. The 
command 'custodia --help' actually prints some help and no longer tries
to load --help as config file. An explicit config file path is required
so 'custodia' without an argument will no longer accidently start a 
Custodia server.

Closes: #34
Closes: #37
Signed-off-by: Christian Heimes <cheimes@redhat.com>

### CODE REVIEW

**Comment by simo5** [comment]
Nack,
please retain /etc/custodia/custodia.conf as the default config file.

**Comment by tiran** [comment]
No, I'm against it. Just the bare command 'custodia' should not attempt to run a service.

**Comment by simo5** [comment]
Then we can close this PR I guess.

**Comment by tiran** [comment]
Please explain why you insist on an implicit default config path.

The custodia command should require an argument to start a server. Just imagine what happens if root accidentally run ``custodia`` instead of ``custodia-cli``, e.g. with ``custo<tab><enter>``. The command will unlink the Unix socket and replace it with a new socket file. A simple typo renders the daemon useless although it seems to be running just fine.

**Comment by simo5** [comment]
It's what most unix daemons do, root should not be silly.
We can add a pid file and check for it if inadvertent run is such a big problem (just like other unix daemons have done in the past for ages.

**Comment by tiran** [comment]
Most daemons listen on a TCP socket and use the bound port as mutex.

**Comment by simo5** [comment]
Sorry but I am not going to merge this unless custodia loads the default config file.
I am ok adding a pid file as a guard if we want a "mutex" of sorts.

**Comment by tiran** [comment]
PID files are hard to get right, e.g. stale PID files. I don't get why you want to replace a simple and straight-forward solution with clear error indicators with a hard, obsolete and fragile technology like PID files.

**Comment by simo5** [comment]
I can do away with PID files, I do not really care, but I prefer to keep the usage of the defaut config file without having to explicitly add it to the command line all the time. I do not see anything wrong in making it easier to just run the binary and have it work.

**Comment by tiran** [comment]
Let's at least fix #34 and make the custodia command more pleasant to use. We can exchange another round of arguments later in #37 :)

**Pull request closed without merging**
